#pragma config(StandardModel, "SQUAREBOT")
#pragma config(RenamedStdModelMotor, port2, r)
#pragma config(RenamedStdModelMotor, port3, l)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[r] = 127;
motor[l] = 127;
wait1Msec(1000);
motor[r] = 0;
motor[l] = 0;
motor[r] = 127;
motor[l] = -127;
wait1Msec(500);
motor[r] = 0;
motor[l] = 0;motor[r] = 127;
motor[l] = 127;
wait1Msec(1000);
motor[r] = 0;
motor[l] = 0;
motor[r] = 127;
motor[l] = -127;
wait1Msec(500);
motor[r] = 0;
motor[l] = 0;motor[r] = 127;
motor[l] = 127;
wait1Msec(1000);
motor[r] = 0;
motor[l] = 0;
motor[r] = 127;
motor[l] = -127;
wait1Msec(500);
motor[r] = 0;
motor[l] = 0;motor[r] = 127;
motor[l] = 127;
wait1Msec(1000);
motor[r] = 0;
motor[l] = 0;
motor[r] = 127;
motor[l] = -127;
wait1Msec(500);
motor[r] = 0;
motor[l] = 0;
while(1 == 1)
  {
    //Get the Latest joystick values
    getJoystickSettings(joystick);
    //Set the driving motors equal to the Y-axis values of the joysticks
    motor[leftMotor] = joystick.joy1_y1;
    motor[rightMotor] = joystick.joy1_y2;
  }
