#pragma config(StandardModel, "SQUAREBOT")
#pragma config(RenamedStdModelMotor, port2, Right)
#pragma config(RenamedStdModelMotor, port3, Left)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[Right] = 127;
motor[Left] = 127;
wait1Msec(7000);


}
