#pragma config(StandardModel, "RVW Buggybot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[rightMotor] = 127;
motor[leftMotor] = 127;
wait1Msec(2000);
motor[rightMotor] = 0;
motor[leftMotor] = 0;
motor[rightMotor] = 127;
wait1Msec(1989);
motor[rightMotor] = 0;
motor[rightMotor] = 127;
motor[leftMotor] = 127;
wait1Msec(1800);
motor[leftMotor] = 0;
motor[rightMotor] = 0;
motor[leftMotor] = 127;
wait1Msec(510);
motor[leftMotor] = 0;
motor[leftMotor] = 127;
motor[rightMotor] = 127;
wait1Msec(1390);
motor[leftMotor] = 0;
motor[rightMotor] = 0;
motor[leftMotor] = 127;
wait1Msec(1890);
motor[leftMotor] = 0;
motor[leftMotor] = 127;
motor[rightMotor] = 127;
wait1Msec(666);
}
