#pragma config(StandardModel, "SQUAREBOT")
#pragma config(RenamedStdModelMotor, port2, rightmotor)
#pragma config(RenamedStdModelMotor, port3, leftmotor)
#pragma config(RenamedStdModelMotor, port6, armmotor)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[rightmotor] = 127;
motor[leftmotor] = 127;
wait1Msec(5000);
motor[armmotor] = 600;

}
