#pragma config(Motor,  port3,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftWheel,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main();
{
	while(1==1)
	{
	motor[port3]=vexRT[2];
	motor[port4]=vexRT[1];
	}
}
