#pragma config(Motor,  port3,           twoWheels,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           opsClaw,       tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
	{
		startMotor(twoWheels, 127);
		//stops when near moveble goal using Wait timers//
		wait(2);
		stopMotor(twoWheels);

		startMotor(opsClaw,-127);
		waitInMilliseconds(500);
		stopMotor(opsClaw);

		startMotor(twoWheels);
		wait(1);
		stopMotor(twoWheels);

	}

}
