#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           verticalScissor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           opsClaw,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main();
{
	while(1==1)
	{
		motor[leftMotor]=vexRT[1];
		motor[rightMotor]=vexRT[2];
		motor[opsClaw]=vexRT[5];
		motor[verticalScissor]=vexRT[4];

	}
}
