#pragma config(Sensor, dgtl1,  solenoid1,      sensorDigitalOut)
#pragma config(Sensor, dgtl2,  solenoid2,      sensorDigitalOut)
#pragma config(Motor,  port2,           RF,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RR,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LF,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LR,            tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while(true)                     // Loop Forever
  {
    if (vexRT[Btn5U] || vexRT[Btn5D] || vexRT[Btn6U] || vexRT[Btn6D])         // If button 6U (upper right shoulder button) is pressed:
    {
      SensorValue[solenoid1] = 1;  // ...activate the solenoid.
      SensorValue[solenoid2] = 1;  // ...activate the solenoid.
    }
    else if (vexRT[Btn7L])
    {
      SensorValue[solenoid1] = 1;
      SensorValue[solenoid2] = 0;
    }
    else if (vexRT[Btn7R])
    {
      SensorValue[solenoid1] = 0;
      SensorValue[solenoid2] = 1;
    }
    else
    {
      SensorValue[solenoid1] = 0;  // ..deactivate the solenoid.
      SensorValue[solenoid2] = 0;  // ..deactivate the solenoid.
    }
    if (vexRT[Btn8L]) {motor[LF] = 100;} else {motor[LF] = vexRT[Ch3];}
    if (vexRT[Btn8U]) {motor[RF] = 100;} else {motor[RF] = vexRT[Ch2];}
    if (vexRT[Btn8D]) {motor[LR] = 100;} else {motor[LR] = vexRT[Ch3];}
    if (vexRT[Btn8R]) {motor[RR] = 100;} else {motor[RR] = vexRT[Ch2];}
    //motor[LR] = vexRT[Ch3];
    //motor[LF] = vexRT[Ch3];
    //motor[RR] = vexRT[Ch2];
    //motor[RF] = vexRT[Ch2];
  }
}
