#pragma config(Sensor, in1,    gyro,           sensorPotentiometer)
#pragma config(Sensor, in14,   red,            sensorLEDtoVCC)
#pragma config(Sensor, in15,   yellow,         sensorLEDtoVCC)
#pragma config(Sensor, in16,   green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightFrontMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           leftFrontMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// from http://www.robotc.net/blog/2011/10/13/programming-the-vex-gyro-in-robotc/
/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++
 Gyro Based Turns - Basic
 -This program instructs your robot to turn for the specified number of degrees in "degrees10".
 -For best sensor results, clear out the gyro and manually configure it at the begging of the code.
 -The Gyro is configured by default to provide values from 0 to -3600 for clockwise rotation,
 and 0 to 3600 for counter-clockwise rotation

Robot Model(s): Swervebot

[I/O Port] [Name] [Type] [Description]
 Motor Port 2 rightMotor VEX Motor Right side motor
 Motor Port 3 leftMotor VEX Motor Left side motor
 Analog Port 8 in8 VEX Gyro Top-center mounted,
 away from the Cortex
 --------------------------------------------------------------------------------------------------*/
  int test = 0;

task main()
 {
 //Completely clear out any previous sensor readings by setting the port to "sensorNone"
 SensorValue[green]=false; SensorValue[yellow]=false; SensorValue[red]=true;
 SensorType[gyro] = sensorNone;
 wait1Msec(1000);
 //Reconfigure Analog Port 8 as a Gyro sensor and allow time for ROBOTC to calibrate it
 SensorType[gyro] = sensorGyro;
 wait1Msec(2000);
 SensorValue[green]=true; SensorValue[yellow]=false; SensorValue[red]=false;

//Adjust SensorScale to correct the scaling for your gyro
 //SensorScale[in8] = 260;
//Adjust SensorFullCount to set the "rollover" point. 3600 sets the rollover point to +/-3600
 //SensorFullCount[gyro] = 3600;

//Specify the number of degrees for the robot to turn (1 degree = 10, or 900 = 90 degrees)
 int degrees10 = 90;


//While the absolute value of the gyro is less than the desired rotation...
 while(abs(SensorValue[gyro]) < degrees10)
 {
   test = SensorValue[gyro];
 //...continue turning
 motor[rightMotor] = 50;
 motor[leftMotor] = -50;
 motor[rightFrontMotor] = 50;
 motor[leftFrontMotor] = -50;
 }

//Brief brake to stop some drift
 motor[rightMotor] = -5;
 motor[leftMotor] = 5;
 motor[rightFrontMotor] = -5;
 motor[leftFrontMotor] = 5;
 wait1Msec(250);

}
