#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  sLimit,         sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           mWrist,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           mShoulder,     tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define ENCODER_CLOSE 10
#define ENCODER_HOLD 5
#define HOME_POWER 40
#define RISE_POWER 75
#define HOLD_POWER 40
#define WRIST_START -127
#define WRIST_EXTEND 127

// function to move arm to specific position and hold it there
void move_to_encoder (int target, int power) {
	while (abs(getMotorEncoder(mShoulder) - target) > ENCODER_CLOSE) { // move until close enough
		motor[mShoulder] = (getMotorEncoder(mShoulder) < target) ? power : -power;
		} // while not close enough
	while (abs(getMotorEncoder(mShoulder) - target) > ENCODER_HOLD) { // move until really close
		motor[mShoulder] = (getMotorEncoder(mShoulder) < target) ? HOLD_POWER : -HOLD_POWER;
		} // while holding
	motor[mShoulder] = 0;
}

task main()
{
  //Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	bLCDBacklight = true;

	//move to starting position
	motor[mWrist] = WRIST_START;
	while (SensorValue(sLimit) == 0) { // move until limit switch pressed
		motor[mShoulder] = -HOME_POWER;
	}
	motor[mShoulder] = 0;

	// respond to right number pad on joystick 1
	while (true) {
	  if (SensorValue(sLimit) == 1)	{ // limit switch pressed
	  	resetMotorEncoder(mShoulder);
	  }
    displayLCDNumber(0, 5, getMotorEncoder(mShoulder), 2);

    if (vexRT[Btn8L]) {move_to_encoder(0, HOME_POWER); motor[mWrist] = WRIST_START;}
    else if (vexRT[Btn8U]) {move_to_encoder(225, RISE_POWER);motor[mWrist] = WRIST_START;}
    else if (vexRT[Btn8R]) {move_to_encoder(500, RISE_POWER); motor[mWrist] = WRIST_EXTEND;}
    else if (vexRT[Btn8D]) {move_to_encoder(725, RISE_POWER); motor[mWrist] = WRIST_EXTEND;}

    // check for second controller
    if (vexRT[Btn8UXmtr2]) {displayLCDPos(1,0); displayNextLCDString("Button on c-2");}
    else {displayLCDPos(1,0); displayNextLCDString("Nothing from c-2");}

  }
}
