#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  sLimit,         sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port3,           mShoulder,     tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  //Clear LCD
	clearLCDLine(0);
	bLCDBacklight = true;

	while (true) {
	  if (SensorValue(sLimit) == 1)	{ // limit switch pressed
	  	resetMotorEncoder(mShoulder);
	  }
    displayLCDNumber(0, 5, getMotorEncoder(mShoulder), 2);
  }
}
