#pragma config(Motor,  port2,           Right,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           Left,          tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Sensor, in1,    gyro,           sensorPotentiometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

#pragma platform(VEX2)
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"

void pre_auton()
{
  bStopTasksBetweenModes = true;
}

#define GYRO_TOLERANCE 5

// angle goes counterclockwise
// this function returns positive if robot should turn right
int SubtractFromCurrHeading(int x) {
    int result = 0;
    int ch = SensorValue[gyro] / 10;
    int diff = abs(ch - x);
    if (diff >= 180) { // more than 180deg apart, so flip
        result = 360 - diff;
        if (x < 180) {
            result = -result;
        }
    } else {
        result = ch - x;
    }
    return result;
}

void CalibrateGyro () {
		//Completely clear out any previous sensor readings by setting the port to "sensorNone"
		SensorType[gyro] = sensorNone;
		wait1Msec(1000);
		//Reconfigure Analog Port 1 as a Gyro sensor and allow time for ROBOTC to calibrate it
		SensorType[gyro] = sensorGyro;
		wait1Msec(2000);
		}

void TurnLeftUsingGyro (int degrees, int speed) {
		CalibrateGyro();
		string displayStr;
		while (abs(SubtractFromCurrHeading(degrees)) > GYRO_TOLERANCE) {
			sprintf(displayStr, "%d", SubtractFromCurrHeading(degrees));
			displayLCDCenteredString(0, displayStr);
			if (SubtractFromCurrHeading(degrees) > 0) {
				displayLCDCenteredString(1, "turning right");
				motor[Right] = -speed;
				motor[Left] = speed;
			}	else if (SubtractFromCurrHeading(degrees) < 0) {
			  displayLCDCenteredString(1, "turning left");
			  motor[Right] = speed;
				motor[Left] = -speed;
			}
		}
		motor[Right] = 0;
		motor[Left] = 0;
		displayLCDCenteredString(1, "done");
}

void TurnRightUsingGyro (int degrees, int speed) {
	TurnLeftUsingGyro (360 - degrees, speed);
}


void TurnStraightUsingGyro (int speed, int secs) {
		CalibrateGyro();
		clearTimer(T1);
		int millisecs = secs * 1000;
		string displayStr;
		while (time1(T1) < millisecs) {
			while (abs(SubtractFromCurrHeading(0)) > GYRO_TOLERANCE) {
				sprintf(displayStr, "%d", SubtractFromCurrHeading(0));
				displayLCDCenteredString(0, displayStr);
				if (SubtractFromCurrHeading(0) > 0) {
					displayLCDCenteredString(1, "adjusting right");
					motor[Right] = 0;
					motor[Left] = speed;
				}	else if (SubtractFromCurrHeading(0) < 0) {
				  displayLCDCenteredString(1, "adjusting left");
				  motor[Right] = speed;
					motor[Left] = 0;
				}
			}
		  motor[Right] = speed;
		  motor[Left] = speed;
			sprintf(displayStr, "%d", time1(T1));
			displayLCDCenteredString(1, displayStr);
	  } // while timer
  	motor[Right] = 0;
		motor[Left] = 0;
		displayLCDCenteredString(1, "done");
}

task autonomous()
{
  	  displayStatusAndTime();
  	  wait1Msec(1000);
  	  TurnLeftUsingGyro (90, 50);
  	  TurnStraightUsingGyro (50, 2);
  	  TurnRightUsingGyro (90, 50);
}

task usercontrol()
{
  while (true)
  {
    UserControlCodePlaceholderForTesting();
  }
}
