#pragma config(Motor,  port2,           Right,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           Left,          tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Sensor, in1,    gyro,           sensorPotentiometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

#define GYRO_TOLERANCE 5

// angle goes counterclockwise
// this function returns positive if robot should turn right
int SubtractFromCurrHeading(int x) {
    int result = 0;
    int ch = SensorValue[gyro] / 10;
    int diff = abs(ch - x);
    if (diff >= 180) { // more than 180deg apart, so flip
        result = 360 - diff;
        if (x < 180) {
            result = -result;
        }
    } else {
        result = ch - x;
    }
    return result;
}

void CalibrateGyro () {
		//Completely clear out any previous sensor readings by setting the port to "sensorNone"
		SensorType[gyro] = sensorNone;
		wait1Msec(1000);
		//Reconfigure Analog Port 1 as a Gyro sensor and allow time for ROBOTC to calibrate it
		SensorType[gyro] = sensorGyro;
		wait1Msec(2000);
		}

void TurnLeftUsingGyro (int degrees, int speed) {
		CalibrateGyro();
		string displayStr;
		while (abs(SubtractFromCurrHeading(degrees)) > GYRO_TOLERANCE) {
			sprintf(displayStr, "%d", SubtractFromCurrHeading(degrees));
			displayLCDCenteredString(0, displayStr);
			if (SubtractFromCurrHeading(degrees) > 0) {
				displayLCDCenteredString(1, "turning right");
				motor[Right] = -speed;
				motor[Left] = speed;
			}	else if (SubtractFromCurrHeading(degrees) < 0) {
			  displayLCDCenteredString(1, "turning left");
			  motor[Right] = speed;
				motor[Left] = -speed;
			}
		}
		motor[Right] = 0;
		motor[Left] = 0;
		displayLCDCenteredString(1, "done");
}

void TurnRightUsingGyro (int degrees, int speed) {
	TurnLeftUsingGyro (360 - degrees, speed);
}


void TurnStraightUsingGyro (int speed, int secs) {
		CalibrateGyro();
		clearTimer(T1);
		int millisecs = secs * 1000;
		string displayStr;
		while (time1(T1) < millisecs) {
			while (abs(SubtractFromCurrHeading(0)) > GYRO_TOLERANCE) {
				sprintf(displayStr, "%d", SubtractFromCurrHeading(0));
				displayLCDCenteredString(0, displayStr);
				if (SubtractFromCurrHeading(0) > 0) {
					displayLCDCenteredString(1, "adjusting right");
					motor[Right] = 0;
					motor[Left] = speed;
				}	else if (SubtractFromCurrHeading(0) < 0) {
				  displayLCDCenteredString(1, "adjusting left");
				  motor[Right] = speed;
					motor[Left] = 0;
				}
			}
		  motor[Right] = speed;
		  motor[Left] = speed;
			sprintf(displayStr, "%d", time1(T1));
			displayLCDCenteredString(1, displayStr);
	  } // while timer
  	motor[Right] = 0;
		motor[Left] = 0;
		displayLCDCenteredString(1, "done");
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/


task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  	  displayStatusAndTime();
  	  wait1Msec(1000);
  	  TurnLeftUsingGyro (90, 50);
  	  TurnStraightUsingGyro (50, 2);
  	  TurnRightUsingGyro (90, 50);

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
    UserControlCodePlaceholderForTesting();
  }
}
