#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           liftMotor1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           liftMotor2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftMotor3,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftMotor4,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           clawMotor,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
motor[leftMotor] = vexRT(Ch3);
motor[rightMotor] = vexRT(Ch2);
	if(vexRT[Btn6U]==1)
	{motor[clawMotor]=127;}
else if (vexRT[Btn6D]==1)
{motor[clawMotor]=-127;}
	if(vexRT[Btn5U]==1)
	{
		motor[liftMotor1]=127;
		motor[liftMotor2]=127;
		motor[liftMotor3]=127;
		motor[liftMotor4]=127;
		}
	else if (vexRT[Btn5D]==1)
	{
		motor [liftMotor1]=-127;
		motor [liftMotor2]=-127;
		motor [liftMotor3]=-127;
		motor [liftMotor4]=-127;
		}
	}
}
