#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           liftMotor1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           liftMotor2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           liftMotor3,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftMotor4,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           clawMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
startMotor (rightMotor, 80);
startMotor (leftMotor, 80);
wait(0.1);
startMotor (rightMotor, -60);
startMotor (leftMotor, -60);
wait(1);
startMotor (leftMotor, 127);
startMotor (rightMotor, 127);
wait(1.5);
	stopMotor (leftMotor);
	stopMotor (rightMotor);
	startMotor (leftMotor, 50);
	startMotor (rightMotor, 50);
	wait(1.5);
	stopMotor (leftMotor);
	stopMotor (rightMotor);
	wait(0.5);
	stopMotor (clawMotor);
	startMotor (leftMotor, 127);
	startMotor (rightMotor, 127);
	wait(1);
	stopMotor (leftMotor);
	stopMotor (rightMotor);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
motor[leftMotor] = vexRT(Ch3);
motor[rightMotor] = vexRT(Ch2);
	if(vexRT[Btn6U]==1)
	{motor[clawMotor]=127;}
else if (vexRT[Btn6D]==1)
{motor[clawMotor]=-127;}
	if(vexRT[Btn5U]==1)
	{
		motor[liftMotor1]=-60;
		motor[liftMotor2]=-60;
		motor[liftMotor3]=-60;
		motor[liftMotor4]=-60;
		}
	else if (vexRT[Btn5D]==1)
	{
		motor [liftMotor1]=127;
		motor [liftMotor2]=127;
		motor [liftMotor3]=127;
		motor [liftMotor4]=127;
		}
}
}
