#pragma config(Motor,  port2,           DriveLF,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           DriveLB,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           DriveRF,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           DriveRB,       tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
  	motor[DriveLF] = vexRT[3];
  	motor[DriveLB] = vexRT[3];
    motor[DriveRF] = vexRT[2];
  	motor[DriveRB] = vexRT[2];
	}

	}
