#pragma config(Motor,  port2,           Left_Front,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           Left_Rear,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           Right_Front,   tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           Right_Rear,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           Tower_Left,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Tower_Right,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Claw_Left,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Claw_Right,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task usercontrol
{
	while(1==1)
	{
		//Drive Motor Controls
		motor[port2] = (vexRT[Ch3]);
		motor[port3] = (vexRT[Ch3]);
		motor[port4] = (vexRT[Ch2]);
		motor[port5] = (vexRT[Ch2]);
		//Tower Motor Controls
		if(vexRT[Btn5U] == 1)       	//If button 5U is pressed...
		{
			motor[port6] = 127;    	//...raise the arm.
			motor[port7] = 127;
		}
		else if(vexRT[Btn5D] == 1)  	//Else, if button 5D is pressed...
		{
			motor[port6] = -127;   	//...lower the arm.
			motor[port7] = -127;
		}
		else                      		//Else (neither button is pressed)...
		{
			motor[port6] = 0;      	//...stop the arm.
			motor[port7] = 0;
			//Claw Motor Controls
			if(vexRT[Btn6U] == 1)       	//If Button 6U is pressed...
			{
				motor[port8] = 127;  		//...close the gripper.
				motor[port9] = 127;
			}
			else if(vexRT[Btn6D] == 1)  	//Else, if button 6D is pressed...
			{
				motor[port8] = -127; 		//...open the gripper.
				motor[port9] = -127;
			}
			else                      		//Else (neither button is pressed)...
			{
				motor[port8] = 0;    		//...stop the gripper.
				motor[port9] = 0;
			}
		}
	}
}
