#pragma config(Motor,  port2,           lowerLeft,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

var draw = function() {
var speed = 65;
motor(lowerLeft,speed);
speed++;
if(speed>75) {
	speed=0;
}
};
