#pragma config(Sensor, dgtl1,  on,             sensorTouch)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           lscissor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rscissor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           cup,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           cdown,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
	{
		//Makes robot go forward//
		untilTouch(on);
		startMotor(leftDrive, 127);
		startMotor(rightDrive, 127);
		//stops when near movable goal//
		stopMotor(leftDrive);
		stopMotor(rightDrive);


	}

}
