#pragma config(Motor,  port2,           Left_Front,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           Left_Rear,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port4,           Right_Front,   tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           Right_Rear,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           Tower_Left,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Tower_Right,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}


task autonomous()
{
startMotor(Right_Front, 127);
startMotor(Left_Front, 127);
wait(2.2);
stopMotor(Right_Front);
stopMotor(Left_Front);
startMotor(Claw, 50);
wait(0.5);
stopMotor(Claw);
startMotor(Tower_Left, 50);
startMotor(Tower_Right, 50);
wait(0.5);
stopMotor(Tower_Left);
stopMotor(Tower_Right);
startMotor(Left_Front, 65);
wait(0.99);
stopMotor(Left_Front);
startMotor(Left_Front, 127);
startMotor(Right_Front, 127);
wait(2.2);
stopMotor(Left_Front);
stopMotor(Right_Front);
startMotor(Claw, -50);
wait(0.5);
stopMotor(Claw);
}





task usercontrol()
{

  while (true)
  {
  	motor[DriveLF] = vexRT[Ch3]; //left front motor
  	motor[DriveLB] = vexRT[Ch3]; //left back motor
    motor[DriveRF] = vexRT[Ch2]; //right forward motor
  	motor[DriveRB] = vexRT[Ch2]; //right back motor
    ///////////////////////////////
  	if(vexRT[Btn6U] == 1)
 {
 motor[Shootout] = 80;
 }
 else if(vexRT[Btn5U] == 1)
 {
 motor[Shootout] = -80;
 }
 else
 {
 motor[Shootout] = 0;
 }
 /////////////////////////////////
 if(vexRT[Btn6D] == 1)
 {
 motor[Santaclaws1] = 80;
 }
 else if(vexRT[Btn5D] == 1)
 {
 motor[Santaclaws1] = -80;
 }
 else
 {
 motor[Santaclaws1] = 0;
 }
/////////////////////////////////
 if(vexRT[Btn6D] == 1)
 {
 motor[Santaclaws2] = 80;
 }
 else if(vexRT[Btn5D] == 1)
 {
 motor[Santaclaws2] = -80;
 }
 else
 {
 motor[Santaclaws2] = 0;
 }
//////////////////////////////
  if(vexRT[Btn8D] == 1)
 {
 motor[Santaclaws3] = 80;
 }
 else if(vexRT[Btn7D] == 1)
 {
 motor[Santaclaws3] = -80;
 }
 else
 {
 motor[Santaclaws3] = 0;
 }
}
}
	}
}

    // Remove this function call once you have "real" code.
