#pragma config(Motor,  port1,           RightBack,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RightFront,    tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           LeftFront,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           WinchLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           WinchRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          LeftBack,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#include "VexellentGyro.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	bStopTasksBetweenModes = true;
}

void forward(float feet, int speed) {
  motor[RightFront] = speed; motor[RightBack] = speed;
  motor[LeftFront] = speed; motor[LeftBack] = speed;
  wait1Msec(feet*speed*8); // time depends on speed (no encoders)
  motor[RightFront] = 0; motor[RightBack] = 0; // stop
  motor[LeftFront] = 0; motor[LeftBack] = 0;
  wait1Msec(250);
}

void raise_lift () {
	motor[WinchLeft] = 50;
	motor[WinchRight] = 50;
	wait1Msec(600);
	motor[WinchLeft] = 0;
	motor[WinchRight] = 0;
  wait1Msec(250);
}

void lower_lift () {
	motor[WinchLeft] = -30;
	motor[WinchRight] = -30;
	wait1Msec(800);
	motor[WinchLeft] = 0;
	motor[WinchRight] = 0;
  wait1Msec(250);
}

task autonomous()
{
	// 1. forward 2 feet
	forward (2, 60);

	// 2. raise lift
	raise_lift();

	// 3. turn 180 degrees
	turn (180); // degrees, positive means left turn

	// 4. forward 4 feet
	forward (4, 60);

	// 5. turn 90 deg left
	turn (90);

	// 6. forward 2 feet
	forward (2, 60);

	// 7. turn 135 deg
	turn (135);

	// 8. forward 4 feet
	forward (4, 60);

	// 9. lower lift
	lower_lift();

}


//////////////////////////////////////////////////////////////////////////


task usercontrol
{
	while(1==1)
	{
		//Drive Motor Controls
	  // front wheel radius = 4.2in., rear wheel radius = 5in
  	// so drive front faster by circumferance ratio = r2/r1 = 1.19

    #define JOYSTICK_DEAD_ZONE 10

	  if (abs(vexRT[Ch3]) < JOYSTICK_DEAD_ZONE) {
	  	motor[LeftBack] = 0; motor[LeftFront] = 0;
	  } else {
	  	motor[LeftBack] = (vexRT[Ch3]);
	  	motor[LeftFront] = (vexRT[Ch3]*1.19);
	  }

	  if (abs(vexRT[Ch2]) < JOYSTICK_DEAD_ZONE) {
	  	motor[RightBack] = 0; motor[RightFront] = 0;
	  } else {
      motor[RightBack] = (vexRT[Ch2]);
		  motor[RightFront] = (vexRT[Ch2]*1.19);
		}

		//Winch Controls
		if(vexRT[Btn5U] == 1)       	//If button 5U is pressed...
		{
			motor[port6] = 120;    	//...raise the arm.
			motor[port7] = 120;
		}
		else if(vexRT[Btn5D] == 1)  	//Else, if button 5D is pressed...
		{
			motor[port6] = -120;   	//...lower the arm.
			motor[port7] = -120;
		}
		else                      		//Else (neither button is pressed)...
		{
			motor[port6] = 0;      	//...stop the arm.
			motor[port7] = 0;
			//Hug Machine Controls

		}
	}
}

/*
////////Controls/////////
//joysticks for moving
//buttons on right side are always up/positive
//btn6U is tower up
//btn5U is tower down
//btn6D is claw open
//btn5D is claw close
*/
