#pragma config(Motor,  port2,           DriveLF,       tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           DriveLB,       tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port4,           DriveRF,       tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           DriveRB,       tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           TowerL,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           TowerR,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}


task autonomous()
{
	//F1
motor[DriveLB] = 90;
motor[DriveLF] = 90;
motor[DriveRF] = 90;
motor[DriveRB] = 90;
wait(1);
 //
motor[DriveLB] = 90;
motor[DriveLF] = 90;
motor[DriveRF] = 90;
motor[DriveRB] = 90;
wait(1);
motor[DriveLB] = 90;
motor[DriveLF] = 90;
motor[DriveRF] = 90;
motor[DriveRB] = 90;
wait(1);
motor[DriveLB] = 90;
motor[DriveLF] = 90;
motor[DriveRF] = 90;
motor[DriveRB] = 90;
wait(1);
}
/*
startMotor(DriveRF, 127);
startMotor(DriveLF, 127);
wait(2.2);
stopMotor(DriveRF);
stopMotor(DriveLF);
startMotor(Claw, 50);
wait(0.5);
stopMotor(Claw);
startMotor(TowerL, 50);
startMotor(TowerR, 50);
wait(0.5);
stopMotor(TowerL);
stopMotor(TowerR);
startMotor(DriveLF, 65);
wait(0.99);
stopMotor(DriveLF);
startMotor(DriveLF, 127);
startMotor(DriveRF, 127);
wait(2.2);
stopMotor(DriveLF);
stopMotor(DriveRF);
startMotor(Claw, -50);
wait(0.5);
stopMotor(Claw);
}
*/

//////////////////////////////////////////////////////////////////////////


task usercontrol
{
	while(1==1)
	{
		//Drive Motor Controls
		motor[port2] = (vexRT[Ch3]);
		motor[port3] = (vexRT[Ch3]);
		motor[port4] = (vexRT[Ch2]);
		motor[port5] = (vexRT[Ch2]);
		//Tower Motor Controls
		if(vexRT[Btn5U] == 1)       	//If button 5U is pressed...
		{
			motor[port6] = 120;    	//...raise the arm.
			motor[port7] = 120;
		}
		else if(vexRT[Btn5D] == 1)  	//Else, if button 5D is pressed...
		{
			motor[port6] = -120;   	//...lower the arm.
			motor[port7] = -120;
		}
		else                      		//Else (neither button is pressed)...
		{
			motor[port6] = 0;      	//...stop the arm.
			motor[port7] = 0;
			//Claw Motor Controls
			if(vexRT[Btn6U] == 1)       	//If Button 6U is pressed...
			{
				motor[port8] = 120;  		//...close the gripper.
				motor[port9] = 120;
			}
			else if(vexRT[Btn6D] == 1)  	//Else, if button 6D is pressed...
			{
				motor[port8] = -120; 		//...open the gripper.
				motor[port9] = -120;
			}
			else                      		//Else (neither button is pressed)...
			{
				motor[port8] = 0;    		//...stop the gripper.
				motor[port9] = 0;
			}
		}
	}
}

/*
while (true)
{
motor[DriveLF] = vexRT[Ch3]; //left front motor
  	motor[DriveLB] = vexRT[Ch3]; //left back motor
    motor[DriveRF] = vexRT[Ch2]; //right forward motor
  	motor[DriveRB] = vexRT[Ch2]; //right back motor
    ///////////////////////////////
  	if(vexRT[Btn6U] == 1)
 {
 motor[TowerL] = 80;
 motor[TowerR] = 80;
 }
 else if(vexRT[Btn5U] == 1)
 {
motor[TowerL] = -80;
 motor[TowerR] = -80;
 }
 else
 {
motor[TowerL] = 0;
 motor[TowerR] = 0;
 }
 /////////////////////////////////
 if(vexRT[Btn6D] == 1)
 {
 motor[Claw] = 80;
 }
 else if(vexRT[Btn5D] == 1)
 {
 motor[Claw] = -80;
 }
 else
 {
 motor[Claw] = 0;
 }
 }
	}
////////Controls/////////
//joysticks for moving
//buttons on right side are always up/positive
//btn6U is tower up
//btn5U is tower down
//btn6D is claw open
//btn5D is claw close
	*/
