#pragma config(Sensor, dgtl1,  autonomousLeft, sensorTouch)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftGear,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightGear,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftClaw,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightClaw,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

// Globals
bool runAutonomousLeft = false;

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...


	if (SensorValue[autonomousLeft]==1) {
  	runAutonomousLeft = true;

  }

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

//task autonomous()
task usercontrol()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

//task usercontrol()
task autonomous()


{
	// User control code here, inside the loop

	while (true)
	{
		motor[leftMotor]  = (vexRT[Ch3])/-2;  // (y + x)/2
		motor[rightMotor] = (vexRT[Ch2])/-2;// (y - x)/2

// Raise, lower or do not move arm
		if(vexRT[Btn5D] == 1)       	//If button 5U is pressed...
		{
			motor[leftGear] = 127;
			motor[rightGear] = 127;			//...raise the arm.
		}
		else if(vexRT[Btn5U] == 1)  	//Else, if button 5D is pressed...
		{
			motor[leftGear] = -127;   	//...lower the arm.
			motor[rightGear] = -127;
			}
		else                      		//Else (neither button is pressed)...
		{
			motor[leftGear] = 0;
			motor[rightGear] = 0;				//...stop the arm.
		}

// Open, close or do not more claw
		if(vexRT[Btn6U] == 1)       	//If Button 6U is pressed...
		{
			motor[leftClaw] = 100;
			motor[rightClaw] = 100;			//...close the gripper.
		}
		else if(vexRT[Btn6D] == 1)  	//Else, if button 6D is pressed...
		{
			motor[leftClaw] = -100;
			motor[rightClaw] = -100;//...open the gripper.
		}
		else                      		//Else (neither button is pressed)...
		{
			motor[leftClaw] = 0;
			motor[rightClaw] = 0;//...stop the gripper.
		}
	}
}
