#pragma config(StandardModel, "RVW CLAWBOT")
#pragma config(RenamedStdModelMotor, port1, l)
#pragma config(RenamedStdModelMotor, port6, claw)
#pragma config(RenamedStdModelMotor, port7, arm)
#pragma config(RenamedStdModelMotor, port10, r)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[r] = 3000;
	motor[l] = 3000;
	wait1Msec(4000);
	motor[r] = 0;
	motor[l] = 0;
	wait1Msec(800);
	motor[r] = 180;
	motor[l] = -180;
	wait1Msec(490);
	motor[r] = 3000;
	motor[l] = 3000;
	wait1Msec(890)




}
