#pragma config(StandardModel, "RVW CLAWBOT")
#pragma config(RenamedStdModelMotor, port1, l)
#pragma config(RenamedStdModelMotor, port6, c)
#pragma config(RenamedStdModelMotor, port7, a)
#pragma config(RenamedStdModelMotor, port10, r)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

motor[l] = 127;
motor[r] = 127;
wait1Msec(1000);
motor[r] = 0;
motor[l] = 0;
wait1Msec(50);
motor[a] = 127;
wait1Msec(1900);
motor[a] = -127;
wait1Msec(50);
motor[r] = -127;
motor[l] = 127;
wait1Msec(480);



}
