#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[rightMotor] = 127;
motor[leftMotor] = 127;
wait1Msec (2500);

motor[rightMotor] = 127;
motor[leftMotor] = 0;
wait1Msec (1250);

motor[rightMotor] = 127;
motor[leftMotor] = 127;
wait1Msec (2250);

motor[rightMotor] = 0;
motor[leftMotor] = 127;
wait1Msec(1250);

motor[rightMotor] = 127;
motor[leftMotor] = 127;
wait1Msec (1050);

motor[rightMotor] = 0;
motor[leftMotor] = 127;
wait1Msec(1250);

motor[rightMotor] = 127;
motor[leftMotor] = 127;
wait1Msec (875);


}
